_:
{
  # Generated by scripts/update-codex-pin.sh from fugu-src 83f099cc678c3d9a88c1b1bcd085ed679ec3b89f.
  version = "0.144.4";
  hashes = {
    x86_64-linux = "sha256-N8mFvp2J6MT0OzqgWUwSE+rCEtMK4rlSIfCP7IB1FdE=";
    aarch64-linux = "sha256-TQckPvSuZ4a4syHXrqP5vk4dLFl65UB+fBuYczNAgrI=";
  };
}
