_:
{
  # Generated by scripts/update-codex-pin.sh from fugu-src 4b77e4cb8c153d01035d63c3e652082d854df4d4.
  version = "0.144.1";
  hashes = {
    x86_64-linux = "sha256-hAka4gxl/MfUEg25fRvVfX/435x2Cft4HHjC671PWig=";
    aarch64-linux = "sha256-ufjvX5jkbO1Nu9N1akIj4+4pmkV/9IijMFvqRV2otbg=";
  };
}
