{
  lib,
  stdenvNoCC,
  fetchurl,
  makeWrapper,
  # Codex uses bubblewrap for its Linux sandbox; without it on PATH it falls
  # back to a bundled copy and warns on every run.
  bubblewrap,
  # Upstream SakanaAI/fugu source. In this flake this is provided by the
  # non-flake input `fugu-src`, so fugu.json is controlled by flake.lock.
  fuguSrc,
  # Override this with pkgs.codex or another pinned Codex package if you do
  # not want to use the bundled upstream binary.
  codexPackage ? null,
  # Generated by scripts/update-codex-pin.sh from the pinned fugu-src input.
  codexPin ? import ./codex-pin.nix {inherit lib;},
  codexVersion ? codexPin.version,
  codexHashes ? codexPin.hashes,
}: let
  targets = {
    x86_64-linux = "x86_64-unknown-linux-musl";
    aarch64-linux = "aarch64-unknown-linux-musl";
  };

  system = stdenvNoCC.hostPlatform.system;

  target =
    targets.${system}
      or (throw "codex-fugu: unsupported system ${system}; supported: ${lib.concatStringsSep ", " (builtins.attrNames targets)}");

  bundledCodex = stdenvNoCC.mkDerivation {
    pname = "codex-bin";
    version = codexVersion;

    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v${codexVersion}/codex-${target}.tar.gz";
      hash = lib.getAttr system codexHashes;
    };

    # The release tarball is flat: it contains the binary at the top level
    # with no wrapping directory, so stdenv's sourceRoot auto-detection fails
    # ("unpacker appears to have produced no directories").
    sourceRoot = ".";

    dontConfigure = true;
    dontBuild = true;

    installPhase = ''
      runHook preInstall

      mkdir -p "$out/bin"

      candidate="$(find . -maxdepth 3 -type f -perm -0100 -name 'codex*' | head -n 1 || true)"
      if [ -z "$candidate" ]; then
        candidate="$(find . -maxdepth 3 -type f -name 'codex*' | head -n 1 || true)"
      fi

      if [ -z "$candidate" ]; then
        echo "codex-bin: could not find codex executable in release archive" >&2
        find . -maxdepth 3 -type f >&2
        exit 1
      fi

      install -m 0755 "$candidate" "$out/bin/codex"

      runHook postInstall
    '';

    meta = {
      description = "OpenAI Codex CLI prebuilt binary";
      homepage = "https://github.com/openai/codex";
      license = lib.licenses.asl20;
      mainProgram = "codex";
      platforms = builtins.attrNames targets;
    };
  };

  codex =
    if codexPackage == null
    then bundledCodex
    else codexPackage;
in
  stdenvNoCC.mkDerivation {
    pname = "codex-fugu";
    version = codexVersion;

    nativeBuildInputs = [makeWrapper];

    dontUnpack = true;

    installPhase = ''
      runHook preInstall

      mkdir -p "$out/bin" "$out/share/codex-fugu"

      install -m 0644 ${fuguSrc}/configs/files/fugu.json \
        "$out/share/codex-fugu/fugu.json"
      install -m 0644 ${fuguSrc}/configs/injects/model_providers.sakana.toml \
        "$out/share/codex-fugu/model_providers.sakana.toml"

      # Modern (Codex >= 0.134.0) profile file. Contains a {{CODEX_HOME}}
      # template token; substitution is user-specific and happens in the
      # Home Manager module, not here.
      install -m 0644 ${fuguSrc}/configs/formats/modern/files/fugu.config.toml \
        "$out/share/codex-fugu/fugu.config.toml"

      makeWrapper ${codex}/bin/codex "$out/bin/codex" \
        --prefix PATH : ${lib.makeBinPath [bubblewrap]}
      makeWrapper ${codex}/bin/codex "$out/bin/codex-fugu" \
        --prefix PATH : ${lib.makeBinPath [bubblewrap]} \
        --add-flags "-p fugu"

      runHook postInstall
    '';

    passthru = {
      inherit codex fuguSrc;
    };

    meta = {
      description = "OpenAI Codex CLI bundled with the SakanaAI Fugu profile wrapper";
      homepage = "https://github.com/SakanaAI/fugu";
      license = lib.licenses.asl20;
      mainProgram = "codex-fugu";
      platforms = builtins.attrNames targets;
    };
  }
