#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "update-codex-pin: missing required command: $1" >&2
    exit 127
  fi
}

need curl
need jq
need nix

lock_json="$(nix flake metadata --json)"
owner="$(jq -r '.locks.nodes["fugu-src"].locked.owner // empty' <<<"$lock_json")"
repo="$(jq -r '.locks.nodes["fugu-src"].locked.repo // empty' <<<"$lock_json")"
rev="$(jq -r '.locks.nodes["fugu-src"].locked.rev // empty' <<<"$lock_json")"

if [[ -z "$owner" || -z "$repo" || -z "$rev" ]]; then
  echo "update-codex-pin: could not read locked fugu-src owner/repo/rev from flake metadata" >&2
  exit 1
fi

bundle_url="https://raw.githubusercontent.com/${owner}/${repo}/${rev}/configs/bundle.sh"
version="$({ curl -fsSL "$bundle_url" || exit 1; } | sed -n 's/^BUNDLE_CODEX_VERSION="\(.*\)"/\1/p')"

if [[ -z "$version" ]]; then
  echo "update-codex-pin: could not read BUNDLE_CODEX_VERSION from $bundle_url" >&2
  exit 1
fi

# $version is remote input (fugu-src bundle.sh) and gets interpolated into a
# release URL whose hash is then committed. Constrain it to a plain semver so
# a malformed or malicious value cannot steer the URL (e.g. via '../').
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "update-codex-pin: BUNDLE_CODEX_VERSION is not a plain semver: '$version'" >&2
  exit 1
fi

declare -A targets=(
  [x86_64-linux]=x86_64-unknown-linux-musl
  [aarch64-linux]=aarch64-unknown-linux-musl
)

declare -A hashes=()
for system in x86_64-linux aarch64-linux; do
  target="${targets[$system]}"
  url="https://github.com/openai/codex/releases/download/rust-v${version}/codex-${target}.tar.gz"
  echo "prefetching ${system}: ${url}" >&2
  hashes[$system]="$(nix store prefetch-file --json "$url" | jq -r '.hash')"
  if [[ -z "${hashes[$system]}" || "${hashes[$system]}" == "null" ]]; then
    echo "update-codex-pin: prefetch did not return a hash for ${system}" >&2
    exit 1
  fi
done

cat > pkgs/codex-fugu/codex-pin.nix <<EOF_PIN
_:
{
  # Generated by scripts/update-codex-pin.sh from fugu-src ${rev}.
  version = "${version}";
  hashes = {
    x86_64-linux = "${hashes[x86_64-linux]}";
    aarch64-linux = "${hashes[aarch64-linux]}";
  };
}
EOF_PIN

echo "updated pkgs/codex-fugu/codex-pin.nix to Codex ${version}" >&2
